Repository Thisarahetz/Calculator-Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#2 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#4 center
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#5 te
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, good-first-issues

#7 Calculator Use aded
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#8 C program to find the number of keywords in a given Text file !!
  To_find_keywords.c
  To_find_keywords.txt
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#9 text colour changed
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#10 page alignment and colours updated
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#12 Calculator UI modified and decimal pointer button added
  css/style.css
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#13 removed unneccecery tags and minimalized html dom
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#14 Calculator celement centered in the page
  index.html
Labels: hacktoberfest-accepted, hacktoberfest, good-first-issues

#15 copyright
  index.html
Labels: hacktoberfest-accepted, hacktoberfest, good-first-issues

#16 Update To_find_keywords.c
  To_find_keywords.c
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#18 Glass Effect
  css/style.css
  index.html
  js/main.js
Labels: hacktoberfest-accepted, hacktoberfest, good-first-issues

#19 Aligned buttons using grid system
  css/style.css
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#20 change fotter background
  css/style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#22 changed header styles
  css/style.css
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#21 reorganized calculator buttons
  css/style.css
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#23 Dineth
  css/style.css
  index.html
  js/main.js
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#24 Calculator-Hacktoberfest2022
  README.md
  To_find_keywords.c
  To_find_keywords.txt
  assets/GitHubDark.svg
  assets/GitHubLight.svg
  assets/MoonIcon.svg
  assets/SunIcon.svg
  assets/calculator.ico
  css/bootstrap/main.css
  css/style.css
  index.html
  js/main.js
  scripts/script.js
  styles/dark.css
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#27 Added a border and padding
  styles/dark.css
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#29 Improve UI #11
  index.html
  styles/dark.css
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#32 Square, Square root and Backspace
  index.html
  scripts/script.js
  styles/dark.css
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#37 Issue#36 improve key input
  scripts/calculate.js
  scripts/script.js
  styles/dark.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#40 added toggleable scientific button. It switches the calculator to scientific mode
  .gitignore
  assets/icons8-root-26.png
  assets/icons8-root-30.png
  index.html
  scripts/calculate.js
  scripts/script.js
  scripts/toggles.js
  styles/dark.css
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#41 Added date and time to calculator in dark and light mode.
  index.html
  styles/dark.css
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#42 footer added
  index.html
  styles/dark.css
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#43 Added footer in caluclator website
  index.html
  styles/dark.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#44 Updated UI of Footer
  index.html
  styles/dark.css
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#45 changed the shape of the result box in light mode
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#46 changed the color palate
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#47 changed the length of result box and placed del and C buttons in new line with On and S buttons
  index.html
  styles/dark.css
  styles/light.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#48 added a toggle button to switch with two light themes
  assets/settings.svg
  index.html
  scripts/script.js
  scripts/toggles.js
  styles/dark.css
  styles/light.css
  styles/theme.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#49 Date and time not updating bug fixed
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#50 display date/time at header
  index.html
  styles/dark.css
  styles/light.css
  styles/theme.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest
